[package]
name = "raydium-mointor"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0.132"
tokio = { version = "1.40.0", features = ["full"]}
